CREATE DATABASE IF NOT EXISTS Faculdade;
USE Faculdade;

DROP TABLE IF EXISTS Aluno;
DROP TABLE IF EXISTS Curso;
DROP TABLE IF EXISTS Professor;
DROP TABLE IF EXISTS Disciplina;
DROP TABLE IF EXISTS Matricula;

CREATE TABLE Aluno (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
data_de_nascimento VARCHAR (20) NOT NULL,
matricula VARCHAR(100) NOT NULL UNIQUE 
);

CREATE TABLE Curso (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
duracao INT NOT NULL,
modalidade ENUM('Presencial', 'EAD', 'Híbrido') NOT NULL
);

CREATE TABLE Professor (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE,
email VARCHAR(100) UNIQUE
);

CREATE TABLE Disciplina (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
carga_horaria INT NOT NULL CHECK (carga_horaria > 0),
id_curso INT NOT NULL,
id_professor INT,
FOREIGN KEY (id_curso) REFERENCES curso(id),
FOREIGN KEY (id_professor) REFERENCES professor(id)
);

CREATE TABLE Matricula (
id INT PRIMARY KEY AUTO_INCREMENT,
id_aluno INT NOT NULL,
id_disciplina INT NOT NULL,
data_matricula DATE DEFAULT (CURRENT_DATE),
status VARCHAR(50) NOT NULL,
FOREIGN KEY (id_aluno) REFERENCES aluno(id),
FOREIGN KEY (id_disciplina) REFERENCES disciplina(id)
);

ALTER TABLE aluno ADD COLUMN nota INT;
ALTER TABLE aluno MODIFY nota INT;

ALTER TABLE Professor MODIFY COLUMN email VARCHAR(100) NOT NULL UNIQUE;

SHOW TABLES;




